### ISSUE TITLE
In the documentation of the sample code , Instead of AccountBalance ,  there should be AccountBalanceInfo

### ISSUE THREAD

**Issue by oseamiya** [Reloadly/reloadly-sdk-java#5]
In the documentation of the sample code  , while supplying crediential there are some mistakes in the documentation :

## Issue
See Here :
https://github.com/Reloadly/reloadly-sdk-java/blob/main/java-sdk-airtime/USAGE.md
`Request<AccountBalance> request = AirtimeAPI.builder()`
It is said to use AccountBalance but there is not any AccountBalance class in the source code instead it will work correct if we use AccountBalanceInfo class.
AccountBalanceInfo class : https://github.com/Reloadly/reloadly-sdk-java/blob/main/java-sdk-airtime/src/main/java/software/reloadly/sdk/airtime/dto/response/AccountBalanceInfo.java

## Links
https://github.com/Reloadly/reloadly-sdk-java/blob/main/java-sdk-airtime/USAGE.md

**Comment by epiard13** [comment]
@oseamiya Thank you for reporting this, we will address this pretty soon in the next release.

**Comment by epiard13** [comment]
> 

@oseamiya We just released version 1.0.2 of the SDK and the documentation has been updated. Thank you
