### ISSUE TITLE
Deprecation of Base64.encode 

### ISSUE THREAD

**Issue by oseamiya** [Reloadly/reloadly-sdk-java#6]
I've used the source code to use Reloadly for developing android application. While using the source-code  ,  I noticed that Base64 to encodeBase64URLSafeString is deprecated as well as I found there is no such method  `Base64.encodeBase64URLSafeString` in Base64 class ..(at org.apache.commons latest library)
This method seems to come from  `org.apache.commons` library  but as far i know , `encodeBase64URLSafeString` should come from `com.google.api.client.util.Base64` and this method `encodeBase64URLSafeString` is depraceted...

See this docs of Base64 : https://googleapis.dev/java/google-http-client/latest/com/google/api/client/util/Base64.html
Use of this method at : https://github.com/Reloadly/reloadly-sdk-java/blob/main/java-sdk-core/src/main/java/software/reloadly/sdk/core/internal/net/Telemetry.java

**Comment by epiard13** [comment]
@oseamiya Thank you for reporting this, we're looking into it.

**Comment by epiard13** [comment]
> I've used the source code to use Reloadly for developing android application. While using the source-code , I noticed that Base64 to encodeBase64URLSafeString is deprecated as well as I found there is no such method `Base64.encodeBase64URLSafeString` in Base64 class ..(at org.apache.commons latest library) This method seems to come from `org.apache.commons` library but as far i know , `encodeBase64URLSafeString` should come from `com.google.api.client.util.Base64` and this method `encodeBase64URLSafeString` is depraceted...
> 
> See this docs of Base64 : https://googleapis.dev/java/google-http-client/latest/com/google/api/client/util/Base64.html Use of this method at : https://github.com/Reloadly/reloadly-sdk-java/blob/main/java-sdk-core/src/main/java/software/reloadly/sdk/core/internal/net/Telemetry.java

@oseamiya We released a new version of the SDK, please check and let me know if you're still having the same issue.
